### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by davewaters** [SuperNEMO-DBD/homebrew-cadfael#24] opened 2017-08-09 11:33 UTC
The installation command: "./bin/brew cadfael-bootstrap" generates a lot of errors, for example:

Error: Invalid formula: /Users/dwaters/supernemo/SOFTWARE/cadfaelbrew/Library/Taps/homebrew/homebrew-core/Formula/ckan.rb

In fact this directory is simply absent, and browsing the source on Github seems to confirm this.

**Comment by drbenmorgan** [comment] 2017-08-09 14:59
Hi @davewaters, I've reproduced and fixed the issue on my (Sierra) Mac. If you do:

```
$ cd /Users/dwaters/supernemo/SOFTWARE/cadfaelbrew
$ git pull
$ ./bin/brew cadfael-bootstrap
```

It should now work - if not, please post the complete output here.

**Comment by drbenmorgan** [comment] 2017-10-12 15:16
Closing issues with no update in 2 months - please reopen if the issue is not resolved.

**Closed by drbenmorgan** 2017-10-12 15:16 UTC
Labels: bug
