### ISSUE TITLE
Error while compiling gettext in cadfael brew

### ISSUE THREAD

**Issue by AlexRed806** [SuperNEMO-DBD/homebrew-cadfael#41] opened 2018-01-15 18:25 UTC
Dear developers,

When I run the cadfael bootstrap I encounter an error while compiling gettext

Undefined symbols for architecture x86_64:
  "_bswap_32", referenced from:
      _write_table in msgfmt-write-mo.o
ld: symbol(s) not found for architecture x86_64

If I try to install gettext with brew manually, there’s no problem.

I am not sure this is related to the installation, although I encountered this only after the recent update to High Sierra (which I am using).

Thank you in advance for your help,
Alessandro

**Comment by drbenmorgan** [comment] 2018-01-16 09:29
What does `brew doctor` show? It's possible this is the same issue as [this old Macports report](https://trac.macports.org/ticket/36688), so worth checking to see if you have the offending `byte swap.h` header.

**Comment by drbenmorgan** [comment] 2018-01-16 16:58
Did you bootstrap in `/usr/local` or elsewhere? Just wondering if you have two homebrew installs going?

Feel free to close if you have a working system!

**Comment by AlexRed806** [comment] 2018-01-17 08:29
I am bootstrapping in a separate cadfael folder (following the quick start instruction).
This because I didn't want brew to mess with my installations of root and geant4 (especially the latter, which is customised).
If there is a way to keep them from being overwritten I'd like to go for it, otherwise I can go for the "global" installation and close.

**Comment by drbenmorgan** [comment] 2018-01-19 11:09
Sorry for the delay - it's probable that the initial error was caused by the mix of files in `/usr/local` and the new local install, so I think you're probably o.k. to go.

Installation in a separate folder is the way to go here. It won't mess with your other installs of ROOT/Geant4 in `/usr/local`, but you will need to take care when using/developing software that the environment variables like `PATH`, `PKG_CONFIG_PATH`, `CMAKE_PREFIX_PATH` and `PYTHONPATH` are set correctly so that the correct set of packages are used.

I am looking at better integration of this tap with core Home/Linuxbrew, but for now it's best to keep them separate.

**Comment by drbenmorgan** [comment] 2018-01-29 16:36
Closing for now - reopen if there are still issues. Also to note that #21 is the main task to provide integration with upstream home/linuxbrew

**Closed by drbenmorgan** 2018-01-29 16:36 UTC
